### ISSUE TITLE
Make <newname> GitHub repositories public by go live date

### ISSUE THREAD

**Issue by aitana16** [finos/legend#227]
# Prior to the launch
- [ ] All project leads reset the project Git history to one single commit, with message `GS open sources project <new name> under FINOS - see https://finos.org/<new name>`

# During the launch
- [ ] Switch visibility of all <new name> repositories from private to public

**Comment by maoo** [comment]
@gs-bracej - I'd like to propose a reset of Git logs for each module, so that, before switching the repositories to public, each repository shows one commit (with the same git message), authored by the module leader.

- For Studio, it would be An
- For SDLC, if would be Kevin
- For Shared, it would be you

Right after that, I'd like to enforce branch protection, which will also prevent force pushes and git history hacks.

What do you think?

**Comment by gs-bracej** [comment]
Sounds perfect to me!

**Comment by aitana16** [comment]
done on Oct 19th
