### ISSUE TITLE
Add branch protection to each module

### ISSUE THREAD

**Issue by maoo** [finos/legend#249]
Enable branch protection across the master branches of all repos; configuration follows:
- Require (2) pull request reviews before merging
- Require (1) review from Code Owners (see note below)
- Require status checks to pass before merging (cla-bot and GitHub Action build/test)
- Require branches to be up to date before merging
- Require linear history - Prevent merge commits from being pushed to matching branches (keeps the Git history clean)
- Include administrators - Enforce all configured restrictions above for administrators
- Restrict who can push to matching branches - finos/alloy-maintainers

Repos to update
- [ ] Shared
- [ ] Studio
- [ ] SDLC
- [ ] PURE
- [ ] Engine

the team would also like to protect master branch from any direct commit, but I can't seem to find a way to achieve this configuration. Will ask help to GitHub on this.

**Comment by brntbeer** [comment]
👋 @maoo I just realized upon second reading of your issue here that you of course know how to set up protected branches, but that you're more curious on the direct committing aspect. I made a nice gif and explanation anyways that i now dont want to lose it =)


 I made a gif to hopefully answer this a bit easier. Basically within each repo there is the "branches" section, from there you can select a branch to add a rule to, and then select all of the settings you want and have specified here. Any one of these settings being enabled will prevent direct pushes onto the branches. 

> * Require status checks to pass before merging (cla-bot and GitHub Action build/test)

One thing to note about this 👆 , the required status checks feature will only show you tooling that has been detected on the repository itself, otherwise it doesnt know of the status to add to the list. So it may be required to have `cla-bot` run first before that particular application can be used as a required status check

![branch-protection](https://user-images.githubusercontent.com/45141/95961282-1bdc9b80-0e05-11eb-9556-8bd1e32f58bc.gif)

**Comment by maoo** [comment]
Thanks @brntbeer !

I've also tested it on cli, to understand which of the checks prevents direct commits, this is what I got:
```
remote: error: GH006: Protected branch update failed for refs/heads/test-branching.
remote: error: At least 1 approving review is required by reviewers with write access.
```

So, the review branch protection is what also prevents direct commits to happen. @gs-bracej @pierredebelen , I hope this answers your question.

**Comment by gs-bracej** [comment]
Yes it does! @maoo Please could you go ahead and apply all these protections to the above repos, and we'll test to confirm?

The only wrinkle is that maven-release-plugin won't be able to commit the pom changes, as it always does that on master and there doesn't seem to be a way to customize that. I have an idea for how we can solve that, I'll follow up with you offline. For the moment it's more important to protect master and have the right review process in place.

**Comment by maoo** [comment]
> Yes it does! @maoo Please could you go ahead and apply all these protections to the above repos, and we'll test to confirm?

We'll have to do it during the launch, as we still don't have teams (and repos) publicly visible.

> The only wrinkle is that maven-release-plugin won't be able to commit the pom changes, as it always does that on master and there doesn't seem to be a way to customize that. I have an idea for how we can solve that, I'll follow up with you offline. For the moment it's more important to protect master and have the right review process in place.

Didn't think of that, bummer. Let's follow up, eager to hear your thoughts.

**Comment by gs-bracej** [comment]
> We'll have to do it during the launch, as we still don't have teams (and repos) publicly visible.

Bummer, OK. Let's do it as early as possible next week then.

**Comment by aitana16** [comment]
Done

**Comment by maoo** [comment]
I'll keep this open to track improvements on branch protection configuration.

**Comment by aitana16** [comment]
done
