### ISSUE TITLE
What is the Legend Platform? 

### ISSUE THREAD

**Issue by agitana** [finos/legend#331]

**Comment by beekemarie** [comment]
Legend is an open sourced end-to-end data management and data governance platform that enables both technical and non-technical users to develop data-centric applications and derive data-driven insights. It provides solutions to data problems that especially firms in the financial industry face on a day-to-day basis – namely gaining access to accurate, complete and timely information. Traditionally, complex financial data is hard to process efficiently and safely which is why data usually ends up scattered across organizational silos. Legend addresses these industry-wide data challenges with its intuitive approach to data modelling and processing. Legend provides both developers and non-developers with access to fast, easy and secure information via intuitive and self-service driven tools. It offers solutions for data discovery, transformation and delivery while ensuring the data consumed is of the highest quality. Legend’s most winning attributes are the easy-to-create data models which describe data in business-friendly terms. The platform is also backed by a powerful Execution Engine, which enables users to leverage their data models in numerous business workflows, and robust Change Management (SDLC), ensuring data models are governed and safe to use in live business processes.

**Comment by agitana** [comment]
thanks @beekemarie
