### ISSUE TITLE
What has been the level of adoption of ISDA’s CDM in the financial industry?

### ISSUE THREAD

**Issue by agitana** [finos/legend#336]

**Comment by beekemarie** [comment]
Currently there is one vendor whose model is considered CDM compliant, while many others are engaged in developing the model such their use case can be supported. An example is the release of DAML Clearing model back in October 2020. https://www.isda.org/2020/10/06/isda-and-digital-asset-launch-cdm-clearing-pilot-using-daml/. Legend will be able to help all participants to engage with CDM and therefore vendor solutions as adoption picks up.

**Comment by TSanborn-ISDA** [comment]
There was significant progress in the adoption of the Common Domain Model (CDM) in 2020 and early 2021.  Most relevant for this forum is the incorporation of the CDM into the Goldman Sachs Legend platform, which was used in FINOS working groups to contribute new components to the CDM in 2020 and is continuing to be used in 2021.(https://www.linuxfoundation.org/en/press-release/goldman-sachs-open-sources-its-data-modeling-platform-through-finos/ )

Additionally, the CDM is being adopted by a number of banks, clearing organizations, technology firms, and regulatory institutions around the world.  Banks are adopting it internally for streamlining portfolio data sharing, regulatory reporting, and other purposes.  

Technology adopters of the CDM include Axoni, who implemented the CDM Equity model to support their trading platform (https://axoni.com/press/axoni-and-regnosys-announce-scala-implementation-of-isda-common-domain-model).  ISDA also recently announced  pilot implementation of the CDM for the clearing of interest rate derivatives using DAML, an open-source smart contract language created by Digital Asset. The Australian Stock Exchange and UBS have been providing input to validate additional functionality of the CDM for this pilot.

Clearing organizations will be using the CDM combined with Distributed Ledger Technologies (DLT) and other solutions for end-to-end processing, clearing, and life cycle management of OTC Derivatives.

Regulatory authorities are working with ISDA and the financial community to insert regulatory reporting code into the CDM in order to facilitate accurate reporting with minimal effort by reporting firms.  An example of this capability was demonstrated in the recent G20 Techsprint, which was won by ISDA and the fintech firm REGNosys who jointly developed a digital regulatory reporting pilot for the Monetary Authority of Singapore.

No additional public information regarding these adoptions is available at this time.

**Comment by agitana** [comment]
thank you @TSanborn-ISDA !
