### ISSUE TITLE
Error Starting Legend Studio 

### ISSUE THREAD

**Issue by katchyben** [finos/legend#370]
## Support Question

.I am trying to setup Legend locally following Maven Installation Guide, I have the Engine, Studio, and SDLC running but when I open the Studio I get the following error.

![Screen Shot 2021-03-19 at 5 35 52 PM](https://user-images.githubusercontent.com/9310096/111875033-03664380-8998-11eb-96f7-b99365009410.png)

What am I doing wrong?
Thanks

**Comment by epsstan** [comment]
@katchyben  Have you been able to get past this issue ? Is it consistently reproducible ? 

The Maven install guide has been updated since this issue was opened.   You might want to try the new guide.
Also, if you are looking to just install and play with Legend, the Docker/Docker compose installers are simpler to set up and get going.

**Comment by epsstan** [comment]
Please reopen if this is still an issue.
