### ISSUE TITLE
Accessing CDM in Local Legend Studio Installation 

### ISSUE THREAD

**Issue by katchyben** [finos/legend#389]
## Support Question

I have successfully installed Legend Studio locally using the Docker Compose option so I have everything running locally but I observe that I don't have access to the CDM or other models. Is there a way to import it or access it in my setup?

**Comment by akphi** [comment]
To clear up a few things here:
1. CDM models are not included with Legend codebase in any manner, so when you setup using Docker Compose, or Maven or whichever way, CDM projects won't be there
2. In order to access CDM model, you need to register an account with FINOS via https://www.finos.org/legend and then you can access http://legend.finos.org/studio . There you should see CDM project
3. Once you can access the project, you can copy the code of the whole project from text-mode in Studio to your local Studio instance so you have it locally.
