### ISSUE TITLE
Bug: Build should enforce using Java: v11.0.10 & above instead of v11 

### ISSUE THREAD

**Issue by cheersmas** [finos/legend#395]
## 🐛 Bug Report

The project when installed using v11 threw a HandShake Exception which has to do with the cacerts file (last release 2018), where the OIDC Class failed to fire a POST request to gitlab server.

### Step to Reproduce

Step reproduceable with SDLC running locally.
1. Install and run the project using v11.
2. visit the http://localhost:7070/api/auth/authorized?mode=prod

### Expected behavior
the above url should authenticate and return `true` on the page.

### Environment
OS: Windows 10
Chrome: Version 89.0.4389.114 (Official Build) (64-bit)

### Possible Solution
Enforce installation of v11.0.10 in pom.xml file for building (or for running too)
![ssl_exception](https://user-images.githubusercontent.com/41203791/114212181-270d2000-997f-11eb-8736-8cc085087a8f.PNG)

**Comment by kevin-m-knight-gs** [comment]
The various legend projects have now been updated to require at least Java 11.0.10 for builds. Note, however, that this doesn't itself restrict the Java version used to run, and the error in question is a result of the Java version used at run time rather than the version used at build time. Still, I would expect most users will run with a version of Java equal to or newer than what they used to build with, so I think this will effectively address the issue.
