### ISSUE TITLE
Issue with the JSON model generation

### ISSUE THREAD

**Issue by pierrelamy** [finos/legend#479]
### Steps to Reproduce:
I have been trying to generate a JSON representation of the model in relation to 3 projects, and encountered validation issues in relation to 2 of those projects, although all those projects were properly compiling from the textual viewer.   (see the attached validation error messages.)
While the error message in the Instance#2 is specific enough to investigate and address the issue, this isn't the case of the Instance#1 (which scope includes the CDM model).

### Expected Result:
I would have expected the validation logic associated with the compiler to catch those issues, which would then make them easier to address.

### Actual Result:
...what actually happened, including full exceptions (please include the entire stack trace, including "caused by" entries), log entries, screen shots etc. where appropriate...

Instance#1
![Screen Shot 2022-01-20 at 15 44 45](https://user-images.githubusercontent.com/22781393/150429495-a55ee4a2-6592-4d38-b99f-8176c29b2810.png)

Instance#2
![Screen Shot 2022-01-20 at 15 58 57](https://user-images.githubusercontent.com/22781393/150429567-fee2ce59-92d8-4d72-ae48-fbd6bcd36429.png)

### Environment:
Studio: 2.3.0
SDLC: 0.6.4.1
Engine: 2.52.2

### Additional Context:
...add any other context about the problem here. If applicable, add screenshots to help explain...

**Comment by pierrelamy** [comment]
As mentioned above, I was able to generate a JSON representation in relation to a 3rd project.  However, after having committed this file creation I tried to access this JSON extract a few days later **without having made any change to the model**, and I am getting the below exception.
Furthermore, when I try to create a new JSON extract, I get this new exception and I'm not able to generate it.
I don't get such issue with Avro and Prototub.

Let me know if you need further information to investigate .

![Screen Shot 2022-01-25 at 16 33 45](https://user-images.githubusercontent.com/22781393/151064100-71f7b3d0-43a7-4cb4-8eca-8c0e2545c8bf.png)

**Comment by pierrelamy** [comment]
I spent quite some time trying to pin down the exact issue.  It appears that there is a bug with the JSON generation whereby it cannot generate complex objects.  I'm able to generate a JSON representation of simple classes, but always get the above mentioned execution error if I try to include the related types.
As mentioned previously, this issue doesn't affect the Avro and Protobuf generation.
I have then renamed the title of this issue.

**Comment by pierrelamy** [comment]
We did upgrade today to the following versions and confirmed that this JSON generation issue also exists with those, while the generation is working fine with Avro and Protobuf:
- Studio: 2.6.0
- SDLC: 0.67.0
- Engine: 2.55.0

**Comment by AFine-gs** [comment]
You can deselect both useConstraints  and includeAllRelatedTypes in the json schema file generation configuration  to bypass the error.  We will improve the error messages for constraints that are incompatible with  the json schema generation.

**Comment by pierrelamy** [comment]
Thank you for looking into this.  To clarify: are you looking to remediate the issue and provide the ability to expose a whole model as a JSON document, or just improve the error message?  Also, can you share some insight into why this issue affects JSON extracts but not Avro, considering that those syntaxes are pretty similar?

**Comment by AFine-gs** [comment]
There are a few things going on here:

- JSON Schema generation processes the functional constraints on a pure class  in order to generate a more complete specification of the model  while the other file generation flavors like Avro do not.  The constraint function processing is a much more complex step - this is compounded by the fact that you can represent constraints in pure that have no equivalent in JSON Schema.  The error in this case was caused by constraints that are not supported in  the processor. Disable useConstraints  bypasses this processing
- For very large models  includeAllRelatedTypes   adds allot of generation time  and you may hit  timeouts when having this checked.  You can leave this checked if it's working for your use case.   This flag puts all related models into a single file in the definitions section.  If you uncheck it then the references will be to other files instead of the same file.  

The roadmap for this feature would be first improve the error message.  The next step would be to offer  either strict generation that raises an error or generation that skips unsupported constraints with a warning.

**Comment by pierrelamy** [comment]
I completely understand that model constraints (as well as derived properties and functions) expressed via the PURE syntax would be excluded from the JSON extract... as well as any other syntax which scope is limited to data representation. 
To be clear, we can make use of the JSON extract by unselecting the constraints, while also limiting the extract to specific objects in the case of a large model.  In that respect, the current issues aren't show-stoppers for us to make use of the JSON extract capability.
My perception is that JSON and Avro are quite close as data representation languages, and I've been surprised by the fact that model generation issues only affect the former.
